# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mixer_auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mixer_auth.proto',
  package='ftl_ma',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10mixer_auth.proto\x12\x06\x66tl_ma\"\n\n\x08\x43heckReq\"-\n\x08\x43heckRsp\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\t\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t23\n\x04\x41uth\x12+\n\x05\x63heck\x12\x10.ftl_ma.CheckReq\x1a\x10.ftl_ma.CheckRspb\x06proto3')
)




_CHECKREQ = _descriptor.Descriptor(
  name='CheckReq',
  full_name='ftl_ma.CheckReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=38,
)


_CHECKRSP = _descriptor.Descriptor(
  name='CheckRsp',
  full_name='ftl_ma.CheckRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='ftl_ma.CheckRsp.err_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='ftl_ma.CheckRsp.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['CheckReq'] = _CHECKREQ
DESCRIPTOR.message_types_by_name['CheckRsp'] = _CHECKRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckReq = _reflection.GeneratedProtocolMessageType('CheckReq', (_message.Message,), {
  'DESCRIPTOR' : _CHECKREQ,
  '__module__' : 'mixer_auth_pb2'
  # @@protoc_insertion_point(class_scope:ftl_ma.CheckReq)
  })
_sym_db.RegisterMessage(CheckReq)

CheckRsp = _reflection.GeneratedProtocolMessageType('CheckRsp', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRSP,
  '__module__' : 'mixer_auth_pb2'
  # @@protoc_insertion_point(class_scope:ftl_ma.CheckRsp)
  })
_sym_db.RegisterMessage(CheckRsp)



_AUTH = _descriptor.ServiceDescriptor(
  name='Auth',
  full_name='ftl_ma.Auth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=87,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='check',
    full_name='ftl_ma.Auth.check',
    index=0,
    containing_service=None,
    input_type=_CHECKREQ,
    output_type=_CHECKRSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['Auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
