# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mixer_auth_pb2 as mixer__auth__pb2


class AuthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.check = channel.unary_unary(
        '/ftl_ma.Auth/check',
        request_serializer=mixer__auth__pb2.CheckReq.SerializeToString,
        response_deserializer=mixer__auth__pb2.CheckRsp.FromString,
        )


class AuthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'check': grpc.unary_unary_rpc_method_handler(
          servicer.check,
          request_deserializer=mixer__auth__pb2.CheckReq.FromString,
          response_serializer=mixer__auth__pb2.CheckRsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ftl_ma.Auth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
